set(CAKE_BINARY_DIR_PREFIX "${CMAKE_CURRENT_LIST_DIR}/b")
set(CAKE_PKG_CLONE_DIR "${CMAKE_CURRENT_LIST_DIR}/c")

set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/o")
set(CMAKE_PREFIX_PATH "${CMAKE_INSTALL_PREFIX}")

